apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}-config
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_BACKEND_URL: {{ .Values.env.NEXT_PUBLIC_BACKEND_URL | quote }}
